// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4G60Qp01bsSBryJ7euez5ZQqNGUd-LiI',
    appId: '1:952932707858:web:db27e1efd32a391bfaf2cb',
    messagingSenderId: '952932707858',
    projectId: 'remidi-pab-609',
    authDomain: 'remidi-pab-609.firebaseapp.com',
    storageBucket: 'remidi-pab-609.firebasestorage.app',
    measurementId: 'G-379L1J0MHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBnC2C5zXN8VQuH9OdV-44lhE_uvSIN8',
    appId: '1:952932707858:android:5f99059448d8b9b7faf2cb',
    messagingSenderId: '952932707858',
    projectId: 'remidi-pab-609',
    storageBucket: 'remidi-pab-609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZF2jsjBj2nQl50Y4unmDZIUGCeMMyD34',
    appId: '1:952932707858:ios:a40f51ca3d4dfb82faf2cb',
    messagingSenderId: '952932707858',
    projectId: 'remidi-pab-609',
    storageBucket: 'remidi-pab-609.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZF2jsjBj2nQl50Y4unmDZIUGCeMMyD34',
    appId: '1:952932707858:ios:a40f51ca3d4dfb82faf2cb',
    messagingSenderId: '952932707858',
    projectId: 'remidi-pab-609',
    storageBucket: 'remidi-pab-609.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4G60Qp01bsSBryJ7euez5ZQqNGUd-LiI',
    appId: '1:952932707858:web:297507e19cb80f19faf2cb',
    messagingSenderId: '952932707858',
    projectId: 'remidi-pab-609',
    authDomain: 'remidi-pab-609.firebaseapp.com',
    storageBucket: 'remidi-pab-609.firebasestorage.app',
    measurementId: 'G-CV3NKTCHTQ',
  );
}
